import "./globals.css";
import Footer from '../components/primary/footer/footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
		<main>
			{children}
		</main>
		<Footer />
	  </body>
    </html>
  )
}
